src/main/java/com/deepdirect/deepwebide_be/member/domain/User.java

- [Feature] User Entity 추가
---
회원가입/로그인/인증을 위한 User Entity 추가
---
---
- Closes #4
---
엔티티 추가 먼저 해보았습니다.
엔티티만 추가하다보니 로컬 테스트는 진행하지 않았습니다.
과정에 따라 순차적으로 만들 예정입니다. 😀

[Feature] User Entity 추가

---

.gitignore
build.gradle
src/main/java/com/deepdirect/deepwebide_be/global/exception/ErrorCode.java
src/main/java/com/deepdirect/deepwebide_be/global/security/JwtTokenProvider.java
src/main/java/com/deepdirect/deepwebide_be/global/security/SecurityConfiguration.java
src/main/java/com/deepdirect/deepwebide_be/member/controller/UserController.java
src/main/java/com/deepdirect/deepwebide_be/member/domain/User.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/request/SignInRequest.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/request/SignUpRequest.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/response/SignInResponse.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/response/SignInUserDto.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/response/SignUpResponse.java
src/main/java/com/deepdirect/deepwebide_be/member/repository/UserRepository.java
src/main/java/com/deepdirect/deepwebide_be/member/service/UserService.java
src/main/java/com/deepdirect/deepwebide_be/member/util/NicknameGenerator.java
src/main/resources/application-env.properties
src/main/resources/application.properties

- [Feature] 회원가입
---
- 회원가입 기능 추가
- 프로필 사진 저장, 이메일 인증, 휴대폰 번호 인증 제외
- 회원가입 실패 시 에러 메세지 출력 처리
- 로그인 요청 시 JWT 토큰 발급
---
---
- Closes #6
---
- 프로필 사진 url 생성, 이메일 인증, 휴대폰 번호 인증 이 세 가지는 미구현된 상태입니다.
회원가입만 만들려다 어쩌다보니 로그인까지 같이 만들었습니다.

[Feature] 회원가입

---

src/main/java/com/deepdirect/deepwebide_be/member/domain/User.java
src/main/java/com/deepdirect/deepwebide_be/repository/domain/Repository.java
src/main/java/com/deepdirect/deepwebide_be/repository/domain/RepositoryEntryCode.java
src/main/java/com/deepdirect/deepwebide_be/repository/domain/RepositoryFavorite.java

- [Feature] Repository 도메인 설계 및 엔티티 구현
---
- Repository 관련 4개 엔티티 설계 및 구현
- 연관관계 설계
- Repository ↔ RepositoryEntryCode, RepositoryMember, RepositoryFavorite (양방향)
- User ↔ Repository, RepositoryFavorite (양방향)
- 모든 엔티티는 Builder 기반으로 생성하며, 연관관계는 서비스 계층에서 수동으로 동기화
- User 도메인에 repositories, favorites 연관관계 추가
---
---
Closes #23 
---

feat(repository): 도메인 설계 및 엔티티 구현

---

src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryController.java
src/main/java/com/deepdirect/deepwebide_be/repository/repository/RepositoryRepository.java
src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Feature] 공유받은 레포지토리 조회
---
- 레포지토리가 공유되어있고,
- 조회하고자 하는 사용자가 레포지토리의 member로 등록되어있는 경우만 모아서 조회가 됨
---
---
예시:
- Closes #19 
- Related to #19 
---
- SharedRepositoryResponse가 조회관련 기능에서 모두 쓰여서 이름을 조회 관련 개발 후에 고칠 예정

feat(공유받은 레포지토리 조회): 공유받은 레포지토리 조회 DP-66

---

src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryController.java
src/main/java/com/deepdirect/deepwebide_be/repository/dto/response/RepositoryListResponse.java
src/main/java/com/deepdirect/deepwebide_be/repository/dto/response/RepositoryResponse.java
src/main/java/com/deepdirect/deepwebide_be/repository/repository/RepositoryRepository.java
src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Feature] 사용자의 전체 레포지토리 조회
---
- 다른 것과 동일하게 정렬된 뒤에 조회됨
- SharedRepositoryResposne와 SharedRepositoryListResponse의 이름에서 Shared를 모두 제거
---
---
예시:
- Closes #27 
- Related to #27 
---
- 좋아요 관련 필터는 즐겨찾기 등록/취소 후에 진행하겠습니다!

feat(사용자의 레포지토리 조회): 사용자의 레포지토리 조회 DP-66

---

src/main/java/com/deepdirect/deepwebide_be/global/exception/ErrorCode.java
src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryController.java
src/main/java/com/deepdirect/deepwebide_be/repository/domain/Repository.java
src/main/java/com/deepdirect/deepwebide_be/repository/dto/request/RepositoryRenameRequest.java
src/main/java/com/deepdirect/deepwebide_be/repository/dto/response/RepositoryRenameResponse.java
src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Feature] 레포지토리 이름 변경 기능 구현
---
- 레포지토리 이름 변경 기능 구현
- Repository.java에 @Setter 추가
- ErrorCode.java에 에러 메시지 추가
- 테스트 완료
---
---
예시:
- Closes #37 
- Related to #37 
---

feat(레포지토리 이름 변경): 레포지토리 이름 변경 DP-78

---

src/main/java/com/deepdirect/deepwebide_be/member/controller/UserController.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/request/EmailCheckRequest.java
src/main/java/com/deepdirect/deepwebide_be/member/dto/response/EmailCheckResponse.java
src/main/java/com/deepdirect/deepwebide_be/member/service/UserService.java

- [Feature] 이메일 중복 확인
---
예시:
- 이메일 중복 확인 API 추가
---
---
- Closes #42
---
많은 지적과 조언 부탁드립니다.

[Feature] 이메일 중복 확인

---

src/main/java/com/deepdirect/deepwebide_be/global/exception/ErrorCode.java
src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryController.java
src/main/java/com/deepdirect/deepwebide_be/repository/repository/RepositoryEntryCodeRepository.java
src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Feature] 공유하기 및 취소하기 기능 구현
---
- 공유 시에 EntryCode 생성, Response에는 포함 X
- 공유할 url과 레포지토리 관련 정보가 나옴\
- 테스트 완료
---
---
- Closes #38 
- Related to #38 
---

feat(공유하기 및 취소하기): 공유하기 및 취소하기 기능 구현 DP-80

---

src/main/java/com/deepdirect/deepwebide_be/repository/domain/Repository.java
src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Fix] 도메인 무결성 관련 위험 해결
---
- @Setter 제거로 인해 깨질 수 있는 도메인 무결성 해결
- sharelink, isshared, repositoryName 관련 변경 할 때의 RepositoryService.java에 수정 + 도메인에서도 수정
---
---
예시:
- Closes #59 
- Related to #59 
---
- repositoryName뿐만 아니라 다른 곳에서도 쓰여지고 있어서 제가 잘못한 부분 다 수정해놨습니답!

fix(도메인 무결성 관련 위험 해결): 도메인 무결성 관련 위험 해결 DP-95

---

.github/workflows/deploy.yml

---
예시:
- 로그인 페이지 폼 구현 (이메일/비밀번호 입력)
- 로그인 요청 시 JWT 토큰 발급 및 저장
---
---
예시:
- Closes #이슈번호
---
예시:

feat(ci/cd): 환경변수 설정 env 추가 DP-102

---

.github/workflows/deploy.yml

---
예시:
- 로그인 페이지 폼 구현 (이메일/비밀번호 입력)
- 로그인 요청 시 JWT 토큰 발급 및 저장
---
---
예시:
- Closes #이슈번호
---
예시:

[deploy] 환경변수 설정 변경

---

.github/workflows/deploy.yml

---
예시:
- 로그인 페이지 폼 구현 (이메일/비밀번호 입력)
- 로그인 요청 시 JWT 토큰 발급 및 저장
---
---
예시:
- Closes #이슈번호
---
예시:

chore(deploy): comment out EC2 deployment script step in workflow

---

.github/workflows/deploy.yml

[deploy] 무중단 배포 테스트 

---

.github/workflows/deploy-zero-downtime.yml
.github/workflows/deploy.yml

chore(deploy): 단일 서버 배포로 롤백

---

.github/workflows/deploy-zero-downtime.yml
.github/workflows/deploy.yml

---
예시:
- 로그인 페이지 폼 구현 (이메일/비밀번호 입력)
- 로그인 요청 시 JWT 토큰 발급 및 저장
---
---
예시:
- Closes #이슈번호
---
예시:

[deploy] 깃액션 도커 엔진엑스

---

src/main/java/com/deepdirect/deepwebide_be/global/security/SecurityConfiguration.java
src/main/java/com/deepdirect/deepwebide_be/member/controller/EmailVerificationController.java
src/main/java/com/deepdirect/deepwebide_be/member/controller/PhoneVerificationController.java
src/main/java/com/deepdirect/deepwebide_be/member/controller/UserController.java
src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryController.java
src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryEntryCodeController.java
src/main/java/com/deepdirect/deepwebide_be/repository/controller/RepositoryFavoriteController.java

fix(cors): cors 설정 업데이트

---

src/main/java/com/deepdirect/deepwebide_be/global/config/SwaggerConfig.java

왜 아무도 나에게 스웨거 주소가 이상하다고 얘기를 해주지 않았는가...

fix(cors): 배포 주소 변경 DP-117

---

src/main/java/com/deepdirect/deepwebide_be/chat/controller/ChatController.java
src/main/java/com/deepdirect/deepwebide_be/chat/domain/ChatMessageReference.java
src/main/java/com/deepdirect/deepwebide_be/chat/dto/response/CodePathListResponse.java
src/main/java/com/deepdirect/deepwebide_be/chat/dto/response/CodeReferenceResponse.java
src/main/java/com/deepdirect/deepwebide_be/chat/service/ChatMessageService.java

- [Feature]코드 참조 파일 경로 조회
---
- request시 폴더 자체도 조회가 되고
- 정렬되어서 보임(폴더명 -> 파일명 순으로)
---
---
예시:
- Closes #130
- Related to #130 
---
테스트 아래 참조 
https://www.notion.so/23f058b1ded880b88759dcc0b9b9fa55?source=copy_link

feat(코드 참조 파일 경로 조회): 코드 참조 파일 경로 조회 DP-141

---

src/main/java/com/deepdirect/deepwebide_be/repository/service/RepositoryService.java

- [Fix] 다른 사용자의 레포지토리 환경설정 페이지 접근 가능 해결
---
- 다른 사용자의 레포지토리를 환경설정 페이지에서 조회했을 때 200 response와 함께 조회가 되는 문제 해결
- 기존 코드의 조건 문이 isShared == false일 경우 조건 전체가 false가 되며, 소유자도 멤버도 아닌 사용자가 접근 가능하게 되는 버그 발생.
- 조건을 멤버인지 아닌지 부터 확인하도록 수정하여, 소유자도 아니고 멤버도 아닌 경우에는 무조건 차단하도록 개선
---
---
예시:
- Closes #147 
- Related to #147
---
- 트러블 슈팅 문서화 및 테스트 결과 
- https://www.notion.so/1-23f058b1ded8805f9cdcf8fb137828c6?source=copy_link

fix(다른 사용자의 레포지토리 환경설정 페이지 접근 가능 해결):  레포지토리 환경설정 페이지 접근 가능 해결 DP-150

---

src/main/java/com/deepdirect/deepwebide_be/global/config/WebSocketConfig.java

Reverts DeepDirect/deepwebide-be#164

Revert "[Deploy] chore(chat): SockJS 와일드카드 허용하지 않음"

---

src/main/java/com/deepdirect/deepwebide_be/chat/dto/request/ChatMessageRequest.java
src/main/java/com/deepdirect/deepwebide_be/chat/service/ChatMessageWriteService.java
src/main/java/com/deepdirect/deepwebide_be/global/exception/ErrorCode.java

---
- ChatMessageRequest에 @notblank 추가
- Service 단 예외처리 추가
- 공통 Error 메세지 추가
---
---
- Closes #185 
- Related to #185 
---
예시:

Fix/dp 178 chat null 값 저장 문제 해결

---

src/main/java/com/deepdirect/deepwebide_be/global/exception/ErrorCode.java
src/main/java/com/deepdirect/deepwebide_be/member/service/PhoneVerificationService.java
src/main/java/com/deepdirect/deepwebide_be/member/service/UserService.java

- [Fix] 휴대전화번호 검증 로직 추가
---
- 휴대전화가 사용되는 함수(인증번호 발송, 회원가입, 아이디/비밀번호 찾기)에 휴대전화 포멧 검증 로직 추가
---
---
예시:
- Closes #189 
- Related to #189 
---
https://www.notion.so/API-240058b1ded880e1a297f7d0da4675fa?source=copy_link

fix(휴대전화번호 검증 로직 추가): 휴대전화번호 검증 로직 추가 DP-180

---

src/main/java/com/deepdirect/deepwebide_be/chat/controller/ChatWebSocketController.java
src/main/java/com/deepdirect/deepwebide_be/chat/domain/ChatMessageReference.java
src/main/java/com/deepdirect/deepwebide_be/chat/dto/request/ChatMessageRequest.java
src/main/java/com/deepdirect/deepwebide_be/chat/dto/request/CodeReferenceRequest.java
src/main/java/com/deepdirect/deepwebide_be/chat/dto/response/ChatMessageBroadcast.java
src/main/java/com/deepdirect/deepwebide_be/chat/service/ChatMessageWriteService.java

- [Fix] 채팅 메시지 요청/응답 구조 명세에 맞게 변경
---
- CodeReferenceRequest 신규 생성
- ChatMessageBroadcast에 codeReference 필드 추가
---
---
예시:
- Closes #이슈번호
---
예시:

fix(chat) 채팅 메시지 요청/응답 구조 명세에 맞게 변경
